/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the archive holds
         * @description Counts for the footers, and the span the archive covers.
         */
        get: operations["getArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/draws/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The newest result available
         * @description Which day that is depends on the clock, and the rule is not simply
         *     "today after 18:35": the balls finish a little earlier, so shortly
         *     before the mark this reaches for today and falls back to yesterday if
         *     the source is not up yet.
         *
         *     That rule lives here rather than in each client. Two copies of a rule
         *     with a time in it are two copies that will disagree.
         */
        get: operations["getLatestDraw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/draws/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One day's result
         * @description Served from the archive when it is there. When it is not, the source is
         *     crawled once and the result stored, so a second request for the same
         *     day is a read. Concurrent requests for one day collapse into a single
         *     crawl.
         */
        get: operations["getDraw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One draw read closely
         * @description Kép, nháy, đầu and đuôi counts, the digits the special touches.
         */
        get: operations["getDayReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/gan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Numbers that have not landed for the longest */
        get: operations["getGan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/frequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How often numbers landed
         * @description Without `group`, one entry per number that appeared. With `group`, the
         *     hundred numbers folded into ten buckets.
         *
         *     Only hits survive the fold. A number's `days` cannot be added across a
         *     bucket, because two numbers in one bucket can land on the same draw and
         *     adding their day counts would count that draw twice.
         */
        get: operations["getFrequency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/number/{lo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything about one two-digit number */
        get: operations["getNumberProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/special-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A month of special prizes */
        get: operations["getSpecialMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draw a made-up board
         * @description Twenty-seven random numbers, plus the order to reveal them in: first
         *     prize down to seventh, then the special last.
         *
         *     POST because each call invents a new board. Nothing is stored, and this
         *     never touches the archive - a client must not be able to confuse a spin
         *     with a result, and keeping the two apart starts here.
         *
         *     Pacing the reveal is the client's business: how fast a message can be
         *     edited is a property of the chat platform, not of the draw.
         */
        post: operations["createSpin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current gold prices
         * @description Cached in core, not in the client. A burst of commands causes one fetch
         *     upstream, and a stale board is served for a while when the source is
         *     failing, because a price from a few minutes ago beats an error message.
         *     Putting that in each client would mean each client getting it slightly
         *     wrong.
         */
        get: operations["getGold"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gold/{code}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily prices for one gold type */
        get: operations["getGoldHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gold/{code}/chart.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The price history as a PNG
         * @description Rendered in core rather than by the client. The chart is drawn from the
         *     same series the history endpoint returns, so a client could draw its
         *     own - but the drawing code already exists here, it is identical for
         *     every client, and a chart that differs between platforms is a bug
         *     nobody would think to look for.
         *
         *     The font is ASCII only, which is why labels with diacritics belong in
         *     the surrounding message rather than on the image.
         */
        get: operations["getGoldChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Channels awaiting the daily announcement */
        get: operations["listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Subscribe a channel
         * @description Idempotent. `created` distinguishes a new subscription from one that
         *     already existed, which is the difference between "đã bật" and "vốn đã
         *     bật" in the reply a person sees.
         */
        put: operations["subscribe"];
        post?: never;
        /**
         * Unsubscribe a channel
         * @description Idempotent. `removed` is false when there was nothing to remove.
         */
        delete: operations["unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/announcements/{date}/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record that the message went out
         * @description Ends the lease. A claim is honoured for ten minutes, after which an
         *     unsent one may be taken over — that is what stops a process dying
         *     between claiming and sending from losing the day for good. Marking it
         *     sent makes the claim permanent.
         */
        put: operations["markAnnounced"];
        /**
         * Claim the right to announce a day to a channel
         * @description Succeeds once per day and channel, across restarts and instances. A
         *     client claims, posts, then marks it sent with PUT; if the post fails it
         *     releases the claim with DELETE so the next run tries again.
         *
         *     The claim is a **lease**, not a permanent mark. If a client dies between
         *     claiming and sending, the row is left behind unsent, and after ten
         *     minutes another attempt may take it over. Without that, one badly timed
         *     crash lost the day for good.
         *
         *     Exactly-once is not on offer: Discord has no idempotency key, so a send
         *     whose response is lost cannot be told from one that never arrived. The
         *     choice is which way to be wrong, and this errs toward silence — a bot
         *     posting the same result twice is more visible than one missing a day,
         *     and the result is still one command away.
         */
        post: operations["claimAnnouncement"];
        /** Give a claim back after a failed send */
        delete: operations["releaseAnnouncement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Switch on this, not on `message`. Wording is for logs and may
             *     change; these values are the contract.
             * @enum {string}
             */
            code: "bad_request" | "out_of_range" | "not_yet" | "no_draw" | "upstream" | "internal" | "already_claimed" | "not_configured" | "too_short";
            /** @description A human-readable detail, for logs. Not display copy. */
            message: string;
        };
        GoldQuote: {
            code: string;
            name: string;
            buy: number;
            /** @description Zero when the source quotes one side only. */
            sell?: number;
            change_buy?: number;
            change_sell?: number;
            currency: string;
        };
        GoldBoard: {
            quotes: components["schemas"]["GoldQuote"][];
            /**
             * Format: date-time
             * @description When the source says the prices were set.
             */
            updated_at: string | null;
            /**
             * Format: date-time
             * @description When core asked. Different from updated_at on a stale board.
             */
            fetched_at: string | null;
            source: string;
        };
        GoldSeries: {
            code: string;
            name: string;
            currency: string;
            /** @description Oldest first. The order is part of the meaning. */
            points: {
                /** Format: date */
                date: string;
                buy: number;
                sell: number;
            }[];
        };
        Subscription: {
            channel_id: string;
            guild_id?: string;
        };
        Archive: {
            draws: number;
            /** @description Days confirmed to have had no draw. */
            absences: number;
            /** @description Subscribed channels. */
            channels: number;
            /** Format: date */
            earliest: string | null;
            /** Format: date */
            latest: string | null;
        };
        Draw: {
            /** Format: date */
            date: string;
            /**
             * @description Vietnamese, e.g. "Thứ Sáu". Naming, not formatting.
             * @example Thứ Sáu
             */
            weekday: string;
            /** @example 50066 */
            special: string;
            /**
             * @description The last two digits of the special prize.
             * @example 66
             */
            de: string;
            /** @description All 27, in board order, special first. */
            numbers: string[];
            /** @description The 27 two-digit tails, sorted. */
            tails: string[];
            /** @description The board as aligned monospace text, no fences. */
            table: string;
            /** @description The đầu đuôi table as aligned monospace text. */
            head_tail: string;
            /** @example xoso.com.vn */
            source: string;
            /** Format: date-time */
            fetched_at: string | null;
        };
        DayReport: {
            /** Format: date */
            date: string;
            de: string;
            cham_dau: number;
            cham_duoi: number;
            tong_de: number;
            /** @description Numbers with two identical digits, each listed once. */
            kep: string[];
            /** @description Numbers that landed more than once. */
            nhay: {
                number: string;
                hits: number;
            }[];
            /** @description Count per first digit, index 0 to 9. */
            heads: number[];
            tails: number[];
            mute_heads: number[];
            mute_tails: number[];
            top_heads: number[];
            top_tails: number[];
            table: string;
        };
        Gan: {
            number: string;
            days: number;
            record: number;
            /** @description The current run has passed the old record. */
            new_record: boolean;
            /** Format: date */
            last_seen: string | null;
            /** Format: date */
            record_end: string | null;
        };
        FrequencyList: {
            /** @enum {boolean} */
            grouped: false;
            /** @description 0 means the whole archive. */
            days: number;
            entries: {
                number: string;
                hits: number;
                /** @description Draws the number appeared in. */
                days: number;
            }[];
        };
        GroupedFrequency: {
            /** @enum {boolean} */
            grouped: true;
            days: number;
            /** @enum {string} */
            group: "dau" | "duoi" | "tong" | "cham";
            buckets: {
                digit: number;
                hits: number;
            }[];
            /** @description Placements counted. Above the numbers drawn when `overlaps`. */
            total: number;
            /** @description total / 10, the flat line the buckets vary around. */
            even: number;
            /** @description True only for `cham`, where one number falls in two buckets. */
            overlaps: boolean;
            table: string;
        };
        Profile: {
            number: string;
            gan: components["schemas"]["Gan"];
            windows: {
                label: string;
                /** @description 0 means the whole archive. */
                days: number;
                /** @description Appearances, counting a number that landed twice as two. */
                hits: number;
                /** @description Draws in the window that held the number at all. */
                draws: number;
                /** @description Draws in the window. */
                total: number;
            }[];
            /** @description Oldest first, one entry per draw in the window. */
            recent: {
                /** Format: date */
                date: string;
                hits: number;
            }[];
            /** @description Mean calendar days between appearances. 0 when unknown. */
            avg_cycle: number;
            /** Format: date */
            first: string | null;
            archive: number;
        };
        SpecialMonth: {
            /** @example 2026-09 */
            month: string;
            days: {
                /** Format: date */
                date: string;
                special: string;
                de: string;
            }[];
            table: string;
        };
        Spin: {
            /** @description All 27, in board order, special first. */
            numbers: string[];
            /**
             * @description Indices into `numbers`, in reveal order. The special is stored
             *     first and revealed last, so this is not 0..26.
             */
            order: number[];
        };
    };
    responses: {
        /** @description Something went wrong */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @example 2026-09-04 */
        DatePath: string;
        /**
         * @description Opaque to core, which never interprets it. Today it is a Discord
         *     channel; a second client would add a platform alongside it rather than
         *     overload this.
         */
        ChannelID: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serving */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    getArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Archive"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLatestDraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A draw */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draw"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 2026-09-04 */
                date: components["parameters"]["DatePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A draw */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draw"];
                };
            };
            /**
             * @description `not_yet` when the source has not published it, `no_draw` when the
             *     day is settled and empty. The two are different: one is worth
             *     asking again for, the other is not.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDayReport: {
        parameters: {
            query?: {
                /** @description Defaults to the newest result available. */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A day report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGan: {
        parameters: {
            query?: {
                /**
                 * @description `lo` counts all 27 numbers; `de` counts only the special prize, so
                 *     its gaps are around a hundred times longer.
                 */
                scope?: "lo" | "de";
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gan entries, longest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gan"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getFrequency: {
        parameters: {
            query?: {
                /** @description Window in days. Omit for the whole archive. */
                days?: number;
                /**
                 * @description `dau` first digit, `duoi` last, `tong` the two added and the last
                 *     digit kept, `cham` either digit. Under `cham` one number falls in
                 *     two buckets, so the buckets total more than the numbers drawn.
                 */
                group?: "dau" | "duoi" | "tong" | "cham";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ungrouped when `group` is absent, grouped when present */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyList"] | components["schemas"]["GroupedFrequency"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNumberProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSpecialMonth: {
        parameters: {
            query?: {
                /** @description `2026-09`. Defaults to the current month. */
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The month, earliest day first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialMonth"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSpin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A spin */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spin"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldBoard"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGoldHistory: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A series, oldest point first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldSeries"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGoldChart: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A chart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            /** @description Fewer than two points, so there is nothing to plot */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every subscription */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Opaque to core, which never interprets it. Today it is a Discord
                 *     channel; a second client would add a platform alongside it rather than
                 *     overload this.
                 */
                channel_id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    guild_id?: string;
                };
            };
        };
        responses: {
            /** @description Subscribed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        channel_id: string;
                        created: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Opaque to core, which never interprets it. Today it is a Discord
                 *     channel; a second client would add a platform alongside it rather than
                 *     overload this.
                 */
                channel_id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unsubscribed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        channel_id: string;
                        removed: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    markAnnounced: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 2026-09-04 */
                date: components["parameters"]["DatePath"];
                /**
                 * @description Opaque to core, which never interprets it. Today it is a Discord
                 *     channel; a second client would add a platform alongside it rather than
                 *     overload this.
                 */
                channel_id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    claimAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 2026-09-04 */
                date: components["parameters"]["DatePath"];
                /**
                 * @description Opaque to core, which never interprets it. Today it is a Discord
                 *     channel; a second client would add a platform alongside it rather than
                 *     overload this.
                 */
                channel_id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claim won; the caller should post */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already claimed; the caller must not post */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    releaseAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 2026-09-04 */
                date: components["parameters"]["DatePath"];
                /**
                 * @description Opaque to core, which never interprets it. Today it is a Discord
                 *     channel; a second client would add a platform alongside it rather than
                 *     overload this.
                 */
                channel_id: components["parameters"]["ChannelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Released */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
